name: .NET Build and Upload Artifact

on: [push, pull_request]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' 

    - name: Build
      run: dotnet build --configuration Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: Vagtplan/bin/Release/net6.0/ 
